---
- name: Deploy chat app to minikube
  hosts: localhost
  tasks:
    - name: Copy secret file
      copy:
        src: ../kubernetes-config/chat-backend-secret.yaml
        dest: /tmp/chat-backend-secret.yaml
    - name: apply secret
      shell: kubectl apply -f /home/lenovo/IdeaProjects/SPE_MAJOR/kubernetes-config/chat-backend-secret.yaml

      # - name: apply backend
    #   shell: >
    #     kubectl apply -f ../kubernetes-config/chat-backend.yaml
    #     --validate=false

    # - name: apply frontend-configmap
    #   shell: >
    #     kubectl apply -f ../kubernetes-config/chat-frontend-configmap.yaml
    #     --validate=false

    # - name: apply frontend
    #   shell: >
    #     kubectl apply -f ../kubernetes-config/chat-frontend.yaml
    #     --validate=false

    # - name: apply ingress
    #   shell: >
    #     kubectl apply -f ../kubernetes-config/chat-ingress.yaml
    #     --validate=false
