---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend-container
          image: rushi4350/chat-backend:backend
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: chat-backend-secret
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: chat-backend-secret
                  key: PORT
